### ISSUE TITLE
Netflix Sign in not working

### ISSUE THREAD

**Issue by Nickspongebobpersonal** [trakt-tools/universal-trakt-scrobbler#395]
I'm Signed in to Netflix, Scrobble, sync and automatic sync is on, but the extension doesn't work and keeps saying I'm not signed in.

**Comment by r3dicalnusz** [comment]
Check #394

**Comment by r3dicalnusz** [comment]
Fixed in v0.4.1

**Comment by joaociocca** [comment]
did it stop working again? I've got 0.4.1 installed and netflix still won't recognize that I'm logged in...
![image](https://github.com/user-attachments/assets/d53b9e39-f382-4f4d-a4ac-47ea8ae4cabf)
![image](https://github.com/user-attachments/assets/8733ef58-efa0-408d-a671-801c787fd31e)
![image](https://github.com/user-attachments/assets/f43be86a-ec8f-4460-bd24-9c494c076777)

**Comment by r3dicalnusz** [comment]
@joaociocca Works fine on my end. Is website access to netflix granted for the extension? Maybe toggle scrobbling and syncing off and on to trigger the query again.

**Comment by joaociocca** [comment]
huh. it seems the permission was removed somewhere since I last used it. weird. Is it possible to implement a check for it on the plugin?

**Comment by MrMamen** [comment]
Closing as this was fixed in v0.4.1.
